name: Tim Reynolds Music
favicon: null
layout_spectrum: 0.8009440416935831
typography_spectrum: 0.8613873329013586
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.3125
  lightness: 0.375
  saturation: 0.10194172477349639
  rhythmicContrast: 0.25
purpose: []
